### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by puddlemoon**
Add option to skip clap build with -DPAULXSTRETCH_ENABLE_CLAP=False

### CODE REVIEW

**Comment by essej** [comment]
Thanks, you should probably have a relevant description text in there instead of the “show all module…” stuff :)

**Comment by puddlemoon** [comment]
Ok, not certain where you mean, but would be happy to add it.

**Comment by essej** [comment]
I mean this:
`option(PAULXSTRETCH_ENABLE_CLAP "Show all module sources in IDE projects" ON) `

Just replace the text in the “” with the real description of the option :)

**Comment by puddlemoon** [comment]
of course...
I´ll close and fix it

**Comment by essej** [comment]
You don’t need to close it, just force push your changes

**Comment by puddlemoon** [comment]
ok, sorry, I completely missed that description :/
and just finding my way here on github

**Comment by baconpaul** [comment]
Neat!

**Comment by puddlemoon** [comment]
Thanks for your help baconpaul..
Not sure it was super helpful with the hand holding but I am very glad to jump in.
hopefully that is all good now. certainly got me up and going :)

**Comment by essej** [comment]
Oops. Anyway, I've now integrated the changes from this into the develop branch manually.

**Pull request merged**
